name: qvapay_api_client
description: Dart API Client which wraps the QvaPay API.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0
  equatable: ^2.0.3
  json_annotation: ^4.1.0

dev_dependencies:
  build_runner: ^2.1.2
  json_serializable: ^5.0.2
  mocktail: ^0.1.4
  test: ^1.17.0
  very_good_analysis: ^2.1.0
